### ISSUE TITLE
No need for the binary_search/position_in_sorted_array

### ISSUE THREAD

**Issue by nimitbhardwaj** [srbcheema1/Algo_Ds#1]
The lower_bound and upper_bound does the work for us, so why using these functions, even lower_bound and upper_bound are more optimized, more general, templates, so prefer them

**Comment by srbcheema1** [comment]
here check the if conditions ... 
it is not always there that always you have to check a numbers position in array ... sometimes it is complex so i need to modify my own fxn (if condition) at that time ...
