### ISSUE TITLE
Add more algorithms and DataStructure application

### ISSUE THREAD

**Issue by srbcheema1** [srbcheema1/Algo_Ds#2]
many algorithms are to be implemented 
these include 
searching algorithms
sorting algorithms
tree traversal
graph algorithms

**Comment by rishabh-bansal** [comment]
Will be working on it!

**Comment by srbcheema1** [comment]
@rishabh-bansal 
try to name your files as filename.cpp
your filenames do not include .cpp at end

**Comment by sirjan13** [comment]
Added code for connected components in Graphs.Plz review PR #53
