### ISSUE TITLE
add any of your algorithm program

### ISSUE THREAD

**Issue by srbcheema1** [srbcheema1/Algo_Ds#4]
make sure that your code is well commented and readable.
all type of algorithms are welcome.

**Comment by Souravirus** [comment]
I am also adding other algorithms

**Comment by geekychaser** [comment]
@srbcheema1 shall i add all the pattern programs?

**Comment by srbcheema1** [comment]
sure . you may go for it  @geekychaser

**Comment by sachincool** [comment]
added some more programs

**Comment by geekychaser** [comment]
@srbcheema1 some patterns algo added .
adding more!

**Comment by srbcheema1** [comment]
thanks @geekychaser  
you are perhaps one of the top contributers of the day

**Comment by geekychaser** [comment]
@srbcheema1 happy to contribute :)

**Comment by NishantTanwar** [comment]
@srbcheema1 There should be a folder of Pattern searching algorithms in strings. Shall I go for it?

**Comment by datkev** [comment]
need any algos in JS?

**Comment by srbcheema1** [comment]
@datkev  you may go for it :)
