### ISSUE TITLE
Restructure folders as to facilitate navigation and contribution

### ISSUE THREAD

**Issue by alexandrebarbaruiva** [srbcheema1/Algo_Ds#74]
Finding files is starting to become quite a chore by itself, maybe it would be easier to separate them into something like
- Data structures
   - stack
      - Python
         - Applications
      - C
         - Applications
      - Java
- Sorting Algorithms
   - bubblesort
      - Python
         - Applications
      - C
      - Java

etc, etc ...

**Comment by srbcheema1** [comment]
thanks for creating the issue @alexandrebarbaruiva 
this would be a great thing for readers to navigate through the files

**Comment by alexandrebarbaruiva** [comment]
#85
