### ISSUE TITLE
Update CONTRIBUTION.md file

### ISSUE THREAD

**Issue by srbcheema1** [srbcheema1/Algo_Ds#89]
you are welcome to give your suggestions regarding and commits regarding CONTRIBUTION.md file 
any kind of contribution is welcome .

**Comment by harshit98** [comment]
Hi @srbcheema1. I would like to write some guidelines while making a contribution. It will teach new contributors in open source -work ethics and the best practices. :)

**Comment by vicennial** [comment]
Hi @srbcheema1 , I opened PR #90 which deals with capitalisation, punctuation, typos and missing words in CONTRIBUTION.md file.

**Comment by srbcheema1** [comment]
thanks for the contriution @vicennial 
happy coding :smile:

**Comment by srbcheema1** [comment]
@haritha1313 
thanks for the contribution .
hope these guidelines help beginners alot :smile:
